relabel_configs:
- source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
  regex: (.+)
  target_label: __scheme__
- source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
  regex: (.+)
  target_label: __metrics_path__
- source_labels:
  - __address__
  - __meta_kubernetes_service_annotation_prometheus_io_port
  regex: ([^:]+)(:\d+)?;(\d+)
  replacement: ${1}:${3}
  target_label: __address__
